version: '2'
services:
  BcliA:
    image: client
    build: ./client/
    links:
      - Bbro
    environment:
      - BROKER_URL=tcp://Bbro:9998
      - CLASSID=A
  BcliB:
    image: client
    build: ./client/
    links:
      - Bbro
    environment:
      - BROKER_URL=tcp://Bbro:9998
      - CLASSID=B
  BcliC:
    image: client
    build: ./client/
    links:
      - Bbro
    environment:
      - BROKER_URL=tcp://Bbro:9998
      - CLASSID=C
      
  BworA:
    image: worker
    build: ./worker/
    links:
      - Bbro
    environment:
      - BROKER_URL=tcp://Bbro:9999
      - CLASSID=A
  BworB:
    image: worker
    build: ./worker/
    links:
      - Bbro
    environment:
      - BROKER_URL=tcp://Bbro:9999
      - CLASSID=B
  BworC:
    image: worker
    build: ./worker/
    links:
      - Bbro
    environment:
      - BROKER_URL=tcp://Bbro:9999
      - CLASSID=C
  BworD:
    image: worker
    build: ./worker/
    links:
      - Bbro
    environment:
      - BROKER_URL=tcp://Bbro:9999
      - CLASSID=D
  Bbro:
    image: broker
    build: ./broker/
    links:
      - Blog
    expose:
      - "9998"
      - "9999"
    environment:
      - LOGGER_URL=tcp://Blog:9995
    ports:
      - "9998:9998"
  Blog:
    image: logger
    build: ./logger/
    expose:
      - "9995"
    volumes:
# /tmp/logger.log DIRECTORY must exist on host and writeable
      - ./Btmp:/tmp/cbwlog
    environment:
      - LOGGER_DIR=/tmp/cbwlog
