version: '2'
services:
  AcliA:
    image: client
    build: ./client/
    links:
      - Abro
    environment:
      - BROKER_URL=tcp://Abro:9998
      - CLASSID=A
  AcliB:
    image: client
    build: ./client/
    links:
      - Abro
    environment:
      - BROKER_URL=tcp://Abro:9998
      - CLASSID=B
  AcliC:
    image: client
    build: ./client/
    links:
      - Abro
    environment:
      - BROKER_URL=tcp://Abro:9998
      - CLASSID=C
  AcliD:
    image: client
    build: ./client/
    links:
      - Abro
    environment:
      - BROKER_URL=tcp://Abro:9998
      - CLASSID=D
      
  AworA:
    image: worker
    build: ./worker/
    links:
      - Abro
    environment:
      - BROKER_URL=tcp://Abro:9999
      - CLASSID=A
  AworB:
    image: worker
    build: ./worker/
    links:
      - Abro
    environment:
      - BROKER_URL=tcp://Abro:9999
      - CLASSID=B
  AworC:
    image: worker
    build: ./worker/
    links:
      - Abro
    environment:
      - BROKER_URL=tcp://Abro:9999
      - CLASSID=C
  Abro:
    image: broker
    build: ./broker/
    links:
      - Alog
    expose:
      - "9998"
      - "9999"
    environment:
      - LOGGER_URL=tcp://Alog:9995
    ports:
      - "9999:9999"
  Alog:
    image: logger
    build: ./logger/
    expose:
      - "9995"
    volumes:
# /tmp/logger.log DIRECTORY must exist on host and writeable
      - ./Atmp:/tmp/cbwlog
    environment:
      - LOGGER_DIR=/tmp/cbwlog
